CREATE TABLE automovel
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    modelo     VARCHAR(255),
    marca      VARCHAR(255),
    ano        INTEGER                                 NOT NULL,
    cor        VARCHAR(255),
    placa      VARCHAR(255),
    preco      DOUBLE PRECISION                        NOT NULL,
    disponivel BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_automovel PRIMARY KEY (id)
);

CREATE TABLE cargo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(255),
    salario      DOUBLE PRECISION,
    nivel_acesso VARCHAR(255),
    CONSTRAINT pk_cargo PRIMARY KEY (id)
);

CREATE TABLE cliente
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    cpf      VARCHAR(255),
    telefone VARCHAR(255),
    email    VARCHAR(255),
    endereco VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE compra
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cliente_id     BIGINT,
    automovel_id   BIGINT,
    funcionario_id BIGINT,
    data_compra    date,
    CONSTRAINT pk_compra PRIMARY KEY (id)
);

CREATE TABLE funcionario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    cpf      VARCHAR(255),
    telefone VARCHAR(255),
    email    VARCHAR(255),
    cargo_id BIGINT,
    endereco VARCHAR(255),
    CONSTRAINT pk_funcionario PRIMARY KEY (id)
);

ALTER TABLE compra
    ADD CONSTRAINT uc_compra_automovel UNIQUE (automovel_id);

ALTER TABLE compra
    ADD CONSTRAINT FK_COMPRA_ON_AUTOMOVEL FOREIGN KEY (automovel_id) REFERENCES automovel (id);

ALTER TABLE compra
    ADD CONSTRAINT FK_COMPRA_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);

ALTER TABLE compra
    ADD CONSTRAINT FK_COMPRA_ON_FUNCIONARIO FOREIGN KEY (funcionario_id) REFERENCES funcionario (id);

ALTER TABLE funcionario
    ADD CONSTRAINT FK_FUNCIONARIO_ON_CARGO FOREIGN KEY (cargo_id) REFERENCES cargo (id);